spring.application.name=language-app
spring.mongodb.uri=mongodb+srv://tonymac129:XasDISelIAAQ5tQD@language-app.qzntbut.mongodb.net/language-app?appName=language-app
spring.mongodb.database=language-app